[package]
name = "async-backtrace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.18.0"
anyhow = "1.0.66"
backtrace = "0.3.66"
gimli = "0.26.2"
memmap2 = "0.5.7"
object = "0.29.0"
rustc-demangle = "0.1.21"
